### ISSUE TITLE
jdk15后无法使用

### ISSUE THREAD

**Issue by langlichong** [antherd/sm-crypto#27]
![image](https://github.com/user-attachments/assets/bbaf2300-2e0d-4533-888b-f4ee2b56f84f)

```
Caused by: java.lang.ExceptionInInitializerError: null
	at com.genew.common.util.CommonCryptogramUtil.doSm4CbcDecrypt(CommonCryptogramUtil.java:97)
	at com.genew.common.handler.CommonSm4CbcTypeHandler.getNullableResult(CommonSm4CbcTypeHandler.java:45)
	at org.apache.ibatis.type.BaseTypeHandler.getResult(BaseTypeHandler.java:85)
```

**Comment by geyiwei-hub** [comment]
https://github.com/antherd/sm-crypto/pull/23
